use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// MCP server transport type, mirrors the original TypeScript ServerConfig
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, sqlx::Type)]
#[serde(rename_all = "kebab-case")]
#[sqlx(type_name = "TEXT", rename_all = "kebab-case")]
pub enum ServerType {
    Stdio,
    Sse,
    #[serde(rename = "streamable-http")]
    StreamableHttp,
    Openapi,
    /// A virtual app-level server (no process / no DB row). Currently the RAG
    /// server, which exposes rag_search/rag_get/rag_tag_search. Builtin
    /// servers are injected into `list_servers` when their feature is enabled
    /// and are otherwise treated like any server by the group aggregation.
    #[serde(rename = "builtin")]
    Builtin,
}

impl Default for ServerType {
    fn default() -> Self {
        Self::Stdio
    }
}

/// Options for MCP server connection behavior
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ServerOptions {
    pub timeout: Option<u64>,
    pub reset_timeout_on_progress: Option<bool>,
    pub max_total_timeout: Option<u64>,
}

/// OpenAPI security configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenApiSecurity {
    #[serde(rename = "type")]
    pub security_type: String,
    pub api_key: Option<OpenApiApiKey>,
    pub http: Option<OpenApiHttpAuth>,
    pub oauth2: Option<OpenApiOAuth2>,
    pub open_id_connect: Option<OpenApiOpenIdConnect>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenApiApiKey {
    pub name: String,
    #[serde(rename = "in")]
    pub location: String,
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenApiHttpAuth {
    pub scheme: String,
    pub credentials: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenApiOAuth2 {
    pub token: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenApiOpenIdConnect {
    pub url: String,
    pub token: String,
}

/// OpenAPI server configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenApiConfig {
    /// URL to fetch the OpenAPI spec from
    pub url: Option<String>,
    /// Inline OpenAPI spec JSON
    pub schema: Option<serde_json::Value>,
    /// OpenAPI version (default "3.1.0")
    #[serde(default = "default_openapi_version")]
    pub version: String,
    /// Security configuration
    pub security: Option<OpenApiSecurity>,
    /// Headers to pass through to the target API
    #[serde(default)]
    pub passthrough_headers: Vec<String>,
}

fn default_openapi_version() -> String {
    "3.1.0".to_string()
}

/// Proxychains4 proxy configuration for STDIO servers (upstream field kept for
/// config round-tripping; the desktop runtime does not yet spawn proxychains).
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ProxychainsConfig {
    pub enabled: Option<bool>,
    /// socks4 | socks5 | http
    #[serde(rename = "type")]
    pub proxy_type: Option<String>,
    pub host: Option<String>,
    pub port: Option<u16>,
    pub username: Option<String>,
    pub password: Option<String>,
    pub config_path: Option<String>,
}

/// Full server configuration stored in DB / returned to frontend
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerConfig {
    // id is auto-generated by the DB; clients don't send it, so default to empty string
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub id: String,
    pub name: String,
    // The frontend uses the key "type" (not "serverType"), so we rename the field here.
    // default = ServerType::Stdio so configs that omit "type" are accepted gracefully.
    #[serde(rename = "type", default)]
    pub server_type: ServerType,
    pub description: Option<String>,
    // stdio fields
    pub command: Option<String>,
    pub args: Option<Vec<String>>,
    pub env: Option<HashMap<String, String>>,
    // http fields
    pub url: Option<String>,
    pub headers: Option<HashMap<String, String>>,
    // connection options
    pub options: Option<ServerOptions>,
    // openapi fields
    pub openapi: Option<OpenApiConfig>,
    /// When true, each downstream HTTP MCP session (`mcp-session-id`) gets its
    /// own dedicated upstream client/connection/process instead of sharing the
    /// pool's single client. Intended for stateful servers (e.g. Playwright).
    /// Frontend sends camelCase `perSessionClient`. Only honored on the HTTP
    /// MCP JSON-RPC path; REST/Tauri direct calls keep the shared pool.
    #[serde(default)]
    pub per_session_client: Option<bool>,
    /// On-demand spawning (stdio only): skip startup connect, spawn the
    /// process lazily on the first tool call, and shut it down automatically
    /// after the idle timeout. Reduces persistent memory usage for rarely-used
    /// servers. Frontend sends camelCase `startOnDemand`.
    #[serde(default)]
    pub start_on_demand: Option<bool>,
    /// Milliseconds of inactivity before shutting down an on-demand stdio
    /// server's process (default: 300000 = 5 min). Frontend sends camelCase
    /// `idleTimeoutMs`.
    #[serde(default)]
    pub idle_timeout_ms: Option<u64>,
    /// Proxychains4 proxy configuration (stdio, Linux/macOS). Round-tripped
    /// from the frontend so an edit of any other field does not drop it.
    #[serde(default)]
    pub proxy: Option<ProxychainsConfig>,
    #[serde(default = "default_true")]
    pub enabled: bool,
}

fn default_true() -> bool { true }

/// Runtime status of a connected MCP server
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerStatus {
    pub name: String,
    pub connected: bool,
    /// True while the server is in the process of starting up (before connect completes).
    #[serde(default)]
    pub starting: bool,
    /// Whether this server is configured for on-demand spawning (sleeping when
    /// disconnected). Cached from the server config so HTTP routing and the
    /// frontend can distinguish "sleeping" from "offline".
    #[serde(default)]
    pub start_on_demand: bool,
    pub tool_count: usize,
    pub error: Option<String>,
    pub last_connected: Option<String>,
    /// Server version reported by the MCP `initialize` handshake
    /// (`serverInfo.version`). Currently only populated for stdio servers.
    /// Used to display the running version next to the server name and to
    /// check for package updates (npx/uvx).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub server_version: Option<String>,
}

/// A single MCP tool exposed by a server
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tool {
    pub name: String,
    pub description: Option<String>,
    pub input_schema: serde_json::Value,
    pub server_name: String,
    /// Whether this tool is enabled (default: true). Set from server_tool_config.
    #[serde(default = "default_true")]
    pub enabled: bool,
    /// MCP 2025-03-26 tool annotations (readOnlyHint / destructiveHint /
    /// idempotentHint / openWorldHint). Passed through from the upstream
    /// server unchanged; None when the upstream omits them.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<serde_json::Value>,
    /// MCP 2025-03-26 output schema. Passed through unchanged; meaningful only
    /// when the tool also returns `structuredContent` on call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_schema: Option<serde_json::Value>,
}

/// Result of a tool invocation
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolCallResult {
    pub content: Vec<serde_json::Value>,
    pub is_error: bool,
    /// MCP 2025-03-26 structured content. Passed through unchanged; present
    /// only when the tool declared an outputSchema and returned structured data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub structured_content: Option<serde_json::Value>,
}

/// Combined server info returned to the dashboard
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerInfo {
    pub config: ServerConfig,
    pub status: ServerStatus,
    pub tools: Vec<Tool>,
    /// Builtin prompts exposed by this server. Populated only for the builtin
    /// "mcphub-desktop" server (which bundles the builtin prompt library); empty
    /// for real MCP servers (their prompts are fetched lazily elsewhere).
    #[serde(default)]
    pub prompts: Vec<crate::models::prompt::BuiltinPrompt>,
    /// Builtin resources exposed by this server. Same as `prompts` - populated
    /// only for the builtin "mcphub-desktop" server.
    #[serde(default)]
    pub resources: Vec<crate::models::resource::BuiltinResource>,
}

/// A page of server-search results: the items on the current page + the total
/// matching count. `page` is 1-based (matches the dashboard list's semantics).
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerPage {
    pub items: Vec<ServerInfo>,
    /// Total matching servers across all pages (NOT just this page).
    pub total: u64,
    pub page: u32,
    pub page_size: u32,
}
